{% set name = "xeus-python-static" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python-wheel/archive/{{ version }}.tar.gz
  sha256: 69694a97b0021e0390a8fbb6620c1517d0d71f6b875c198c7a9b123e2adcc9c7

build:
  number: 0
  skip: true  # [(win and vc<14) or ppc64le or py36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pkg-config                             # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make                                   # [unix]
  host:
    - pip
    - python
    - scikit-build >=0.11.0,<0.12
    - libuuid                                # [linux]
    - perl                                   # [win]
    - nasm                                   # [win]
  run:
    - python
    - ipython  >=7.20,<8
    - debugpy >=1.1.0,<2.0  # [py>=37]
    - pygments  >=2.3.1,<3
  run_constrained:
    # Add a run constraint on xeus-python 0.0.0 making it impossible to install both
    - xeus-python =0.0.0

test:
  imports:
    - xpython
  commands:
    - test -f ${PREFIX}/share/jupyter/kernels/xpython/kernel.json                      # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 1)    # [win]
    - if exist %PREFIX%\\bin\\concrt140.dll (exit 1)                                   # [win]
    - if exist %PREFIX%\\bin\\msvcp140.dll (exit 1)                                    # [win]
    - if exist %PREFIX%\\bin\\msvcp140_1.dll (exit 1)                                  # [win]
    - if exist %PREFIX%\\bin\\msvcp140_2.dll (exit 1)                                  # [win]
    - if exist %PREFIX%\\bin\\vcruntime140.dll (exit 1)                                # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Python language based on Xeus (static build)
  description: xeus-python is a Jupyter kernel for the Python language based on the Xeus library, a native implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter-xeus/xeus-python-wheel

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
